name: Build and deploy ASP.Net Core app to Azure Web App - bulksparks-mvc-dotnetmastery

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/MyProject/MyProject.csproj

      - name: Build with dotnet
        run: dotnet build src/MyProject/MyProject.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish src/MyProject/MyProject.csproj --configuration Release --output ${{ github.workspace }}/myapp --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8CCFCF0F797D4172ACE3E4D7D6516641 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D0947E668F364942869F833C56D75DAA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_64B58CB986924382BA1DDD237FC57FD8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bulksparks-mvc-dotnetmastery'
          package: ${{ github.workspace }}/myapp
